### ISSUE TITLE
[BUG] Docs site appears to be down

### ISSUE THREAD

**Issue by NatElkins** [koculu/ZoneTree#105]
**Describe the bug**
https://tenray.io doesn't appear available.

**To Reproduce**
Navigate to https://tenray.io/docs/ZoneTree/api/Tenray.ZoneTree.Segments.Disk.KeyHead.html

See the following:

<img width="754" alt="image" src="https://github.com/user-attachments/assets/db7e0676-c2fe-44fc-b4b1-40fd83810dab">

**Expected behavior**
Docs should be available.

**Screenshots**
See above

**please complete the following information:**
 - Operating System: MacOS
 - ZoneTree Version: N/A

**Comment by koculu** [comment]
Thanks for reporting this.
The URL that you have provided has never been available because the XML docs are not generated for this internal struct.

The main site:
https://zonetree.dev/

Getting Started: 
https://zonetree.dev/docs/getting-started/
