### ISSUE TITLE
[FEATURE] ARM support.

### ISSUE THREAD

**Issue by dvakor** [koculu/ZoneTree#14]
**Is your feature request related to a problem? Please describe.**
ZoneTree does not support ARM arch in this moment. Try to run it on M1 and get `PlatformNotSupportedException` in `Crc32Computer` :(

**Describe the solution you'd like**
Would be great if we can run it on ARM

**Additional context**
According to the unit tests, it is enough to fix the Crc32Computer, so if you need help, I can make PR in the next few days.

**Comment by koculu** [comment]
Hi @dvakor,
It would be great if you contribute to that,
since I don't have M1 Hardware.
