### ISSUE TITLE
[Enhancement] Reduce CPU cycles on Crc32Computer

### ISSUE THREAD

**Issue by koculu** [koculu/ZoneTree#17]
**What kind of enhancement you would like to have? Please describe.**
This is a performance improvement request.

**Describe the enhancement you'd like**
Crc32Computer checks CPU architecture for every byte.  Reduce the unnecessary conditional CPU instructions.

**Comment by sgf** [comment]
maybe we need XXHash  will be better (in .net XXHash will come in .net 8.0 )?

**Comment by koculu** [comment]
We use CPU instructions to calculate Crc32. I am not sure if it would make a difference.

**Comment by sgf** [comment]
> We use CPU instructions to calculate Crc32. I am not sure if it would make a difference.

You are right, crc32 can get hardware acceleration.
