### ISSUE TITLE
[BUG] Seek method for ReverseIterator is not working

### ISSUE THREAD

**Issue by aley1** [koculu/ZoneTree#19]
**Describe the bug**

ReverseIterator Seek method does not work correctly. It does not move the iterator to the location of the prefix. Instead it just iterate in reverse starting at the very end of the database.

**To Reproduce**
using var revIterator = zoneTree.CreateReverseIterator();
    revIterator.Seek("myPrefix");
    count = 0;
    while (revIterator.Next())
    {
        var key = revIterator.CurrentKey;
        var value = revIterator.CurrentValue;
        Console.WriteLine($"{key} : {value}");
        count++;
        if (count > 10)
        {
            break;
        }
    }

**Expected behavior**
After running .Seek("myPrefix"), the ReverseIterator should start iterating from the location of the first key with the prefix.

**please complete the following information:**
 - Operating System: Windows 10
 - ZoneTree Version: 1.5.8

**Comment by koculu** [comment]
@aley1 
could you please provide the data to reproduce the issue?
Thanks.

**Comment by koculu** [comment]
Added prefix search tests using iterators forward/backward: https://github.com/koculu/ZoneTree/pull/20
Everything is working as expected.
Please note the following implementation details. 

```
ReverseIterator.Seek => SeekToLastSmallerOrEqualElement(key)
Iterator.Seek => SeekToFirstGreaterOrEqualElement(key)
```

Seek methods are implemented symmetrically.

Please let me know if you reproduce an issue according to the definition above of Seek method,
with all necessary reproduction steps, including your key and values.

**Comment by aley1** [comment]
Hi @koculu 

Please try the following code:

`static void TestZTRevereIterator()
{
    using var zoneTree = new ZoneTreeFactory<string, int>()
   .SetComparer(new StringCurrentCultureComparerAscending()) 
   .SetKeySerializer(new Utf8StringSerializer())
   .SetValueSerializer(new Int32Serializer())
   .OpenOrCreate();

    for (var i = 0; i < 50; ++i)
    {
        zoneTree.Upsert($"myprefix1|string{i}", i);
    }   
    for (var i = 0; i < 50; ++i)
    {
        zoneTree.Upsert($"myprefix2|string{i}", i);
    }
    for (var i = 0; i < 50; ++i)
    {
        zoneTree.Upsert($"myprefix3|string{i}", i);
    }   
    for (var i = 0; i < 50; ++i)
    {
        zoneTree.Upsert($"myprefix4|string{i}", i);
    }
 
    zoneTree.Maintenance.MoveMutableSegmentForward();
    zoneTree.Maintenance.StartMergeOperation()?.Join();

    string myKey;
    int myValue;
    int count = 0;

    using var iterator = zoneTree.CreateIterator();
    iterator.Seek("myprefix2");
    count = 0;
    while (iterator.Next())
    {
        var key = iterator.CurrentKey;
        var value = iterator.CurrentValue;
        Console.WriteLine($"{key} : {value}");
        count++;
        if (count > 5)
        {
            break;
        }
    }

    Console.WriteLine();
    using var revIterator = zoneTree.CreateReverseIterator();
    revIterator.Seek("myprefix2");
    count = 0;
    while (revIterator.Next())
    {
        var key = revIterator.CurrentKey;
        var value = revIterator.CurrentValue;
        Console.WriteLine($"{key} : {value}");
        count++;
        if (count > 5)
        {
            break;
        }
    }   
 
}`

The code produces the following result:

_myprefix2|string0 : 0
myprefix2|string1 : 1
myprefix2|string10 : 10
myprefix2|string11 : 11
myprefix2|string12 : 12
myprefix2|string13 : 13

myprefix4|string9 : 9
myprefix4|string8 : 8
myprefix4|string7 : 7
myprefix4|string6 : 6
myprefix4|string5 : 5
myprefix4|string49 : 49_

I was expecting that for ReverseIterator, it will start iterating backwards from 'myprefix2' but it is going to the end of the database and starting from there.
Maybe I am not clear about how it should work but is this the expected behavior?

**Comment by aley1** [comment]
Also, just want to add another unexpected behavior (for me at least), if you run these codes with the data above, none of them produce any result. I was expecting that it should start iterating from myprefix1|..... onwards.
`  
 using var iterator = zoneTree.CreateIterator();
    iterator.Seek("myprefix");
    count = 0;
    while (iterator.Next())
    {
        var key = iterator.CurrentKey;
        var value = iterator.CurrentValue;
        Console.WriteLine($"{key} : {value}");
        count++;
        if (count > 5)
        {
            break;
        }
    }

using var iterator = zoneTree.CreateIterator();
    iterator.Seek("myprefix1");
    count = 0;
    while (iterator.Next())
    {
        var key = iterator.CurrentKey;
        var value = iterator.CurrentValue;
        Console.WriteLine($"{key} : {value}");
        count++;
        if (count > 5)
        {
            break;
        }
    }`

**Comment by koculu** [comment]
Thank you @aley1 for reporting this.
Could you please test the PR for your scenarios? I tested the code you shared in the code and it works now.
The problem was in the sparse array optimization logic for both iterators.

**Comment by aley1** [comment]
@koculu 
I've tested the fix and it is working correctly now. :)
