### ISSUE TITLE
`FileSystem.ReplaceFile` fails if there are FileSystemWatchers applied to the directory

### ISSUE THREAD

**Issue by hach-que** [koculu/ZoneTree#24]
**Describe the bug**
Under certain circumstances, `FileSystem.ReplaceFile` can fail:
```
System.IO.IOException: Unable to remove the file to be replaced.
         at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
         at Tenray.ZoneTree.AbstractFileStream.LocalFileStreamProvider.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
         at Tenray.ZoneTree.AbstractFileStream.DurableFileWriter.WriteAllBytes(String path, Byte[] bytes)
         at Tenray.ZoneTree.Core.ZoneTreeMetaWAL`2.SaveMetaData(ZoneTreeMeta zoneTreeMeta, Int64 mutableSegment, Int64 diskSegment, Int64[] readOnlySegments, Int64[] bottomSegments, Boolean createNew)
         at Tenray.ZoneTree.Core.ZoneTreeLoader`2.LoadZoneTreeMetaWAL()
         at Tenray.ZoneTree.Core.ZoneTreeLoader`2.LoadZoneTree()
         at Tenray.ZoneTree.ZoneTreeFactory`2.OpenOrCreate()
```
The Internet seems to suggest that this call can fail if there are any FileSystemWatchers applied to the directory, which can happen incidentally due to various programs (VSCode, etc.)

**To Reproduce**
The Internet suggests this can be replicated by setting up a FileSystemWatcher in another program: https://stackoverflow.com/questions/46824487/unable-to-remove-the-file-to-be-replaced-error-during-file-replace-if-filesys

**Expected behavior**
ZoneTree should fall back to Delete/MoveFile if ReplaceFile fails.

**please complete the following information:**
 - Operating System: Windows
 - ZoneTree Version: 1.6.0

**Comment by koculu** [comment]
Hi, @hach-que,

Thank you for reporting this issue.

I understand that you want to use a fallback method using MoveFile / DeleteFile, but please note that this is not the recommended way of solving this issue. 

ReplaceFile operation is an atomic operation that is executed at the operation system level.
Changing it with custom MoveFile / DeleteFile operation breaks the atomicity, which can cause unexpected data loss in case of power cut or crashes.

The best solution in your case is to move your data folder out of the file system watchlist region.
Please also make sure that the metafile is not opened by any other process.
In an ideal world, your data folder should not be accessed by other processes. 
In production, you can protect your data folder by giving read/write access to a specific user/group and by running the process with privileged user/group.

If you understand the circumstances of not using ReplaceFile method and still want to use a fallback method using MoveFile / DeleteFile, you can create your custom class that implements the IFileStreamProvider interface and pass your custom file stream provider to the ZoneTreeFactory constructor.

I hope this helps. Let me know if you have any other questions.

**Comment by hach-que** [comment]
It should be possible to do a recoverable MoveFile operation with something like. As long as you're consistently calling File.Replace based on the presence of `current`, it should work.

```csharp
if (File.Exists(destination))
{
  File.Delete(destination);
}
if (File.Exists(current))
{
  File.Move(current, destination, true);
}
```

In our case though, I'll just override `LocalFileStreamProvider` because I know it's safe (we know there isn't another instance of the process running, so the only thing that could cause `File.Replace` to fail is a filesystem watcher).

**Comment by koculu** [comment]
If your process terminates in the middle, your destination file will be missing.
Although the current file stays there with a temporary name, the application won't find the destination file on the next run.

It can be recovered automatically by changing the loading logic to lookup a secondary file name.

Let's see if your custom class solves the problem. Then we can reconsider to include it in ZoneTree by addressing the issue above.
