### ISSUE TITLE
[BUG] Int64Serializer deserializes to Int32

### ISSUE THREAD

**Issue by frabul** [koculu/ZoneTree#25]
**Describe the bug**
```
namespace Tenray.ZoneTree.Serializers;

public sealed class Int64Serializer : ISerializer<long>
{
    public long Deserialize(byte[] bytes)
    {
        return BitConverter.ToInt32(bytes);
    }

    public byte[] Serialize(in long entry)
    {
        return BitConverter.GetBytes(entry);
    }
}
```
 
**Expected behavior**
Deserialize to int64

**Comment by koculu** [comment]
The following types are just aliases of each other.

**long is Int64
int is Int32
short is Int16**

This is not a valid bug description.

**Comment by koculu** [comment]
Thank you @frabul 
I did not check the implementation at first glance, and marked this invalid. 
Now I see the bug and it will be fixed soon :)
