### ISSUE TITLE
Benchmark comparison to SQLite

### ISSUE THREAD

**Issue by opcodewriter** [koculu/ZoneTree#41]
In the README it says "hundreds of times faster than SQLite". But I could not see any benchmark for SQLite.

**Comment by koculu** [comment]
From official SQLite site:

> 19) INSERT is really slow - I can only do few dozen INSERTs per second
> 
> Actually, SQLite will easily do 50,000 or more [INSERT](https://www.sqlite.org/lang_insert.html) statements per second on an average desktop computer. But it will only do a few dozen transactions per second. Transaction speed is limited by the rotational speed of your disk drive. A transaction normally requires two complete rotations of the disk platter, which on a 7200RPM disk drive limits you to about 60 transactions per second.

https://www.sqlite.org/faq.html#:~:text=Actually%2C%20SQLite%20will%20easily%20do,speed%20of%20your%20disk%20drive.

ZoneTree achieves 5M insertions per second. I need time to conduct a proper benchmark. Currently, the numbers are based on documentation and there is a possibility of inaccuracies.

**Comment by opcodewriter** [comment]
@koculu Thanks, I wasn't aware of that documentation from SQLite... For the future, maybe having an actual benchmark with SQLite will be worthy...
