### ISSUE TITLE
ZoneTree vs MS Garnet comparison 

### ISSUE THREAD

**Issue by MedAnd** [koculu/ZoneTree#62]
Hi, I came across your project recently and found it interesting. 

More a question actually; I am wondering how ZoneTree compares to [MS Garnet ](https://microsoft.github.io/garnet/)both in terms of performance and features?

Thx.

**Comment by koculu** [comment]
Hi @MedAnd ,

Thanks for your interest in ZoneTree!

ZoneTree and MS Garnet serve different purposes. Garnet is a server application that supports the Redis protocol, whereas ZoneTree is a library implementing LSM Tree.

Comparison of these products does not make sense to me.

Thanks.

**Comment by MedAnd** [comment]
Hi @koculu  - what are the main use cases where you see ZoneTree excelling?

**Comment by koculu** [comment]
I think the Wikipedia article explains this concept more effectively: [Log-structured merge-tree](https://en.wikipedia.org/wiki/Log-structured_merge-tree)
